stages:
  - build
  - test
  - deploy

.default_tags:
  tags: [deepath, supervisor, stage_1, env_alpha]

build-job:
  stage: build
  tags: !reference [.default_tags, tags]
  artifacts:
    paths:
      - deepath
  script:
    - echo "Compiling the code..."
#    - dub build -bdebug --parallel
    - dub build -brelease --parallel
    - strip -s deepath
    - echo "Compile complete."

test-job:
  stage: test
  tags: !reference [.default_tags, tags]
  script:
    - echo "Running tests..."
    - ls -l deepath
    - echo "Tests complete."

deploy-job:
  stage: deploy
  tags: !reference [.default_tags, tags]
  script:
    - echo "Application successfully deployed."
