stages:
  - build
  - test
  # - deploy

variables:
  build_type:
    value: release
    description: "^ choose build type ('debug' or 'release') ^"
  build_mechanism:
    value: default
    description: "^ choose build mechanism ('default' or 'container_ldc') ^"

.default_tags:
  tags: [deepath, supervisor, stage_1, env_alpha]

badge:
  stage: build
  tags: !reference [.default_tags, tags]
  script: |
    anybadge -l "ldc version" -v "$(ldc2 --version | head -n1 | grep -oP '(?<=\().*(?=\))')" -f ldc-version.svg -c green
  artifacts:
    paths:
      - ldc-version.svg
    when: always
    expire_in: 5y weeks

build-app:
  stage: build
  tags: !reference [.default_tags, tags]
  artifacts:
    paths:
      - deepath
  script:
    - declare -A a_build_type=([debug]=1 [release]=1)
    - '[[ ! -n ${a_build_type["${build_type}"]} ]] && echo "Wrong build type." && exit 1'
    - declare -A a_build_mechanism=([default]=1 [container_ldc]=1)
    - '[[ ! -n ${a_build_mechanism["${build_mechanism}"]} ]] && echo "Wrong build type." && exit 1'
    - echo "Compiling the code..."
    - '[[ "${build_mechanism}" == default ]] && dub build -b "${build_type}" --parallel'
    - '[[ "${build_mechanism}" == container_ldc ]] && podman run --rm -it -v .:/src docker.io/vreitech/ldc:latest dub build -b "${build_type}" --parallel'
    - strip -s deepath
    - echo "Compile complete."

test-app:
  stage: test
  tags: !reference [.default_tags, tags]
  script:
    - echo "Running tests..."
    - ls -l deepath
    - echo "Tests complete."

# deploy:
#   stage: deploy
#   tags: !reference [.default_tags, tags]
#   script:
#     - echo "Application successfully deployed."
