stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - dub build -bdebug --parallel
    - echo "Compile complete."

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - ls -l deepath
    - echo "Tests complete."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
